/* ═══════════════════════════════════════════════════════════════════════
   HASNAIN STUDIO X: AI Studio gallery data
   AUTO-GENERATED by update-gallery.js, last run: file count 10

   To add artwork:   drop files into the "images" folder,
                     then double-click update-gallery.bat

   You may hand-edit any "title", "desc", "tag" or "alt" below.
   re-running the tool keeps your edits and only adds/removes files.
   ═══════════════════════════════════════════════════════════════════════ */
window.GALLERY_IMAGES = [
  {
    "src": "images/gallery/artgenstudio__Autumn-Treehouse__Painted-concept-illustration.png",
    "tag": "artgenstudio",
    "title": "Autumn Treehouse",
    "desc": "Painted Concept Illustration",
    "alt": "Autumn Treehouse, AI artwork by Hasnain Studio X",
    "w": 2432,
    "h": 1664
  },
  {
    "src": "images/gallery/artgenstudio__Hoard-Keeper__Stylised-3D-character-render.png",
    "tag": "artgenstudio",
    "title": "Hoard Keeper",
    "desc": "Stylised 3D Character Render",
    "alt": "Hoard Keeper, AI artwork by Hasnain Studio X",
    "w": 2432,
    "h": 1664
  },
  {
    "src": "images/gallery/artgenstudio__Coast-Road-1955__Vintage-colour-photography-look.png",
    "tag": "artgenstudio",
    "title": "Coast Road 1955",
    "desc": "Vintage Colour Photography Look",
    "alt": "Coast Road 1955, AI artwork by Hasnain Studio X",
    "w": 1216,
    "h": 832
  },
  {
    "src": "images/gallery/nostalgicel__Blood-Moon-Gate__Selective-colour-over-monochrome.png",
    "tag": "nostalgicel",
    "title": "Blood Moon Gate",
    "desc": "Selective Colour Over Monochrome",
    "alt": "Blood Moon Gate, AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/nostalgicel__Cobalt-Portrait__High-detail-character-study.png",
    "tag": "nostalgicel",
    "title": "Cobalt Portrait",
    "desc": "High Detail Character Study",
    "alt": "Cobalt Portrait, AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/nostalgicel__Crimson-Armour__Retro-anime-cel-with-ink-linework.png",
    "tag": "nostalgicel",
    "title": "Crimson Armour",
    "desc": "Retro Anime Cel With Ink Linework",
    "alt": "Crimson Armour, AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/artgenstudio__Snow-Leopard-At-Dawn__Photorealistic-wildlife-study.png",
    "tag": "artgenstudio",
    "title": "Snow Leopard At Dawn",
    "desc": "Photorealistic Wildlife Study",
    "alt": "Snow Leopard At Dawn, AI artwork by Hasnain Studio X",
    "w": 2432,
    "h": 1664
  },
  {
    "src": "images/gallery/QuantumGenAI-Image2.png",
    "tag": "quantumxai",
    "title": "Open Sky Portrait",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image1.png",
    "tag": "quantumxai",
    "title": "Gilded Renaissance",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image.png",
    "tag": "quantumxai",
    "title": "Ornate Portrait Study",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  }
];
