/* ═══════════════════════════════════════════════════════════════════════
   HASNAIN STUDIO X — AI Studio gallery data
   AUTO-GENERATED by update-gallery.js — last run: file count 3

   To add artwork:   drop files into the "images" folder,
                     then double-click update-gallery.bat

   You may hand-edit any "title", "desc", "tag" or "alt" below —
   re-running the tool keeps your edits and only adds/removes files.
   ═══════════════════════════════════════════════════════════════════════ */
window.GALLERY_IMAGES = [
  {
    "src": "images/gallery/QuantumGenAI-Image2.png",
    "tag": "quantumxai",
    "title": "Open Sky Portrait",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image1.png",
    "tag": "quantumxai",
    "title": "Gilded Renaissance",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image.png",
    "tag": "quantumxai",
    "title": "Ornate Portrait Study",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  }
];
