/* ═══════════════════════════════════════════════════════════════════════
   HASNAIN STUDIO X — AI Studio gallery data
   AUTO-GENERATED by update-gallery.js — last run: file count 6

   To add artwork:   drop files into the "images" folder,
                     then double-click update-gallery.bat

   You may hand-edit any "title", "desc", "tag" or "alt" below —
   re-running the tool keeps your edits and only adds/removes files.
   ═══════════════════════════════════════════════════════════════════════ */
window.GALLERY_IMAGES = [
  {
    "src": "images/gallery/artgenstudio__Snow-Leopard-At-Dawn__Photorealistic-wildlife-study.png",
    "tag": "artgenstudio",
    "title": "Snow Leopard At Dawn",
    "desc": "Photorealistic Wildlife Study",
    "alt": "Snow Leopard At Dawn — AI artwork by Hasnain Studio X",
    "w": 2432,
    "h": 1664
  },
  {
    "src": "images/gallery/QuantumGenAI-Image2.png",
    "tag": "quantumxai",
    "title": "Open Sky Portrait",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image1.png",
    "tag": "quantumxai",
    "title": "Gilded Renaissance",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/QuantumGenAI-Image.png",
    "tag": "quantumxai",
    "title": "Ornate Portrait Study",
    "desc": "",
    "alt": "AI artwork by Hasnain Studio X",
    "w": 1024,
    "h": 1024
  },
  {
    "src": "images/gallery/artgenstudio__Gilded-Bloom__Botanical-still-life-in-low-light.png",
    "tag": "artgenstudio",
    "title": "Gilded Bloom",
    "desc": "Botanical Still Life In Low Light",
    "alt": "Gilded Bloom — AI artwork by Hasnain Studio X",
    "w": 896,
    "h": 1216
  },
  {
    "src": "images/gallery/artgenstudio__Breath-Apart__Airbrushed-graphic-novel-portrait.png",
    "tag": "artgenstudio",
    "title": "Breath Apart",
    "desc": "Airbrushed Graphic Novel Portrait",
    "alt": "Breath Apart — AI artwork by Hasnain Studio X",
    "w": 1216,
    "h": 832
  }
];
